### ISSUE TITLE
0.0.2 release

### ISSUE THREAD

**Issue by samuelcolvin** [bokeh/Bokeh.jl#14]
* [x] #6 better documentation, 
* [x] probably need to host the examples somewhere, @bryevdv said they could go on http://bokeh.pydata.org
* [x] #5 (partially done on #12) get more sophisticated glyhps working
* [x] clean up the readme
* [ ] axis labels.
* [x] remove [bokeh_bindings.md](https://github.com/bokeh/Bokeh.jl/blob/master/doc/other/bokeh_bindings.md) and clean up docs. bokeh_bindings.md will remain in the repo history if it's ever needed in future.
* [ ] fix js tests properly as per #11
* [ ] basic support for DataFrames as input arguments to `plot`
* [ ] some basic docs using [docile](https://michaelhatherly.github.io/Docile.jl)
* [ ] get rid of tabs and remove indents from modules

**Comment by samuelcolvin** [comment]
as per #13 the aim is to get this ready for mid February to coincide with Bokeh v0.8.

Maybe best to have a release before that which works with v0.7 then, then just fix any conflicts with v0.8 once it's released?

**Comment by bryevdv** [comment]
There should be very little if any changes like happened with 0.7 and `glyphspec`s, so optimistically anything you base on current code should also work with 0.8. I would say it's at least worth testing this a few times with `master` leading up to 0.8, it would be good to know whether there are any problems earlier rather than later. 

We can definitely host docs on `bokeh.pydata.org` or prominently link to docs hosted elsehwere, or both. I'm not sure if it makes sense for you to try and adopt the same Sphinx style the current main site uses. If you'd like to let me know I am happy to help. We will eventually have to figure out a mechanism that would allow you to deploy the docs on your own, but for now I would suggest starting with our fabfile as a template, and for now I can just run it with my creds to deploy your docs whenever you like. The easiest scenario will be if all your docs live under a single dir that the fabfile can just rsync. 

We are also thinking of splitting off the docs into a separate repo. If we did that we could either build up  all the docs for all languages with git subtrees, or we could give people write access to the docs repo to contribute their docs directly. Do you have any thoughts on what would be easiest/best for you?

**Comment by samuelcolvin** [comment]
I think simplest for me to build and deploy the docs myself then we don't need to faff about with permissions etc., you can link to them and then in future if it becomes clear that it would be best to have the docs in one places we can move them across.

I might as well use a github site. I should be able to build the site using the `gh-pages` branch and keep the package clean.

I also build [Julia By Example](http://www.scolvin.com/juliabyexample/) to I might add a simple example of Bokeh.jl and link to the docs.

**Comment by bryevdv** [comment]
Linking will work perfectly as well :)

**Comment by bryevdv** [comment]
@samuelcolvin just checking in. We are on track for a 0.8 release on the 17th. I am going to add a section in the main bokeh docs linking to all the new language bindings. If you have anything in particular you would like the `bokeh.jl` section to say, please let me know. As always if there is anything we can do to help, let us know that too.

**Comment by samuelcolvin** [comment]
It's still very rough, but I've made a start on Bokeh.jl's main omission; a help site: [bokeh.github.io/Bokeh.jl](http://bokeh.github.io/Bokeh.jl/). 

I'll try and fill it out tomorrow.

**Comment by bryevdv** [comment]
Looks great! Ler me know if there is anything we can help with.

**Comment by samuelcolvin** [comment]
I'm going to close this as I've released a new version. I'll work on the remaining points when I get a chance.

Nothing in particular I need help with, any feedback on the docs and the interface generally would be appreciated.
